For review
xosmig/aush pull request #1
Opened 2018-06-13 12:51 UTC by xosmig

2018-06-15 06:32 UTC, yurii-litvinov requested changes
В целом всё круто, но хочется больше встроенных команд. Например, в винде echo реализована как встроенная команда шелла, поэтому попытка вызывать её как внешний процесс заканчивается неуспехом. Хочется echo, wc, cat как встроенные команды, чтобы несчастные пользователи Windows тоже могли пользоваться этим шеллом.

2018-06-15 06:32 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/commands/executor/StandardCommandExecutor.java
> +                // oops
Мм. Хоть что-то сделать нужно, так оно вообще все исключения проглатиывать будет. Если ничего не должно бросать исключения внутри, лучше выкинуть RuntimeException, если должно, то ловить что-то конкретное

2018-06-15 06:32 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/environment/Inherit.java
> +public final class Inherit {
Я бы сказал, что этим классам тоже нужна документация

2018-06-15 06:32 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/textui/TextUserInterface.java
> +    public Environment environment;
Для dependency injection не лучше ли использовать конструктор или в крайнем случае геттеры-сеттеры?

2018-06-19 11:20 UTC, yurii-litvinov requested changes
На команде `> echo 123 | wc` шелл повисает. На `> echo 123 | cat` не повисает, но ничего не делает. Ожидается, что cat выведет свой входной поток.

```
> echo '123$x'
'1231'
```
А должно быть `123$x`

Поправьте, пожалуйста.

2018-06-19 11:20 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/ShellInternalError.java
> +public class ShellInternalError extends RuntimeException {
Я бы сказал, что этому классу тоже надо комментарий.

2018-06-19 11:20 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/utils/Reference.java
> +}
Класс явно не из мира Java :) В Java вроде как идеоматично использовать массивы из одного элемента для этих целей. Впрочем, это можно не править, мне так больше нравится.

2018-06-19 11:20 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/utils/Utils.java
> +public final class Utils {
Тоже надо комментарии же

2018-06-19 11:20 UTC, yurii-litvinov commented on src/test/java/com/xosmig/swdesignhw/aush/commands/executor/StandardCommandExecutorTest.java
> +}
Тестовое покрытие не впечатляет. Cat, Exit и Pwd не покрыты вообще.

2018-06-19 11:20 UTC, yurii-litvinov commented on src/test/java/com/xosmig/swdesignhw/aush/commands/executor/StandardCommandExecutorTest.java
> +        assertOutput("hello, world!\n");
Хардкодить переносы строк в Java идеологически неверно. У меня вот ни один тест не прошёл

2018-06-19 11:20 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/environment/Inherit.java
> +public final class Inherit {
Напоминаю

2018-06-19 17:32 UTC, xosmig commented on src/test/java/com/xosmig/swdesignhw/aush/commands/executor/StandardCommandExecutorTest.java
> +        assertOutput("hello, world!\n");
Сделал тесты windows-совместимыми и добавил виндовый CI

2018-06-19 17:32 UTC, xosmig commented on src/main/java/com/xosmig/swdesignhw/aush/ShellInternalError.java
> +public class ShellInternalError extends RuntimeException {
Done.

2018-06-19 17:34 UTC, xosmig commented on src/main/java/com/xosmig/swdesignhw/aush/utils/Reference.java
> +}
Fixed.

2018-06-19 17:41 UTC, xosmig commented on src/main/java/com/xosmig/swdesignhw/aush/utils/Utils.java
> +public final class Utils {
Done.

2018-06-19 19:38 UTC, xosmig commented
@yurii-litvinov в целом, все пофиксил, добавил немного тестов. А вот одинарные кавычки мне поддерживать не хотелось бы. Это обязательно?
Вообще, у баша довольно кривая и неинтуитивная семантика кавычек и экранирования, которую довольно сложно воспроизвести.

2018-06-19 20:10 UTC, xosmig commented
@yurii-litvinov добавил одинарные кавычки, это оказалось не так страшно, как я почему-то думал.

2018-06-20 16:13 UTC, yurii-litvinov approved these changes
Да, всё теперь очень годно (правда, часть про парсеры так и осталась без комментариев). Зачтена.

2018-06-20 16:13 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/environment/CloseableInput.java
> + * Nobody is going to read this comment anyway.
:)

2018-06-20 16:13 UTC, yurii-litvinov commented on src/main/java/com/xosmig/swdesignhw/aush/environment/Environment.java
> +        public boolean shouldExit;
А зачем они public?

2018-06-20 16:23 UTC, xosmig commented on src/main/java/com/xosmig/swdesignhw/aush/environment/Environment.java
> +        public boolean shouldExit;
Хм, какой-то артефакт прошлого, спасибо.

2018-06-20 17:09 UTC, closed without merging